version: '3.7'
volumes:
  database:
services:
  db:
    image: mysql:latest
    container_name: votacao-mysql
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=votacao
      - MYSQL_DATABASE=votacao
      - MYSQL_USER=votacao
      - MYSQL_PASSWORD=votacao

  service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    container_name: votacao-api
    image: votacao-api
    ports:
      - 8080:8080
    environment:
      spring.datasource.jdbc.url: "jdbc:mysql://db:3306/votacao"