version: '3.7'
volumes:
  database:
services:
  db:
    image: mariadb:latest
    container_name: votacao-mariadb
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=votacao
      - MYSQL_DATABASE=votacao
      - MYSQL_USER=votacao
      - MYSQL_PASSWORD=votacao
