version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=voting
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data:
    driver: local