version: "3"

services:
  postgres-compose:
    image: postgres:12.4-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "votacao"
    ports:
      - "5432:5432"

