services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: votacao
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - my-network

    pgadmin:
            image: dpage/pgadmin4:latest
            restart: always
            environment:
                PGADMIN_DEFAULT_EMAIL: admin@email.com
                PGADMIN_DEFAULT_PASSWORD: admin
                PGADMIN_LISTEN_PORT: 80
            ports:
                - "8090:80"
            volumes:
                - pgadmin-data:/var/lib/pgadmin
            depends_on:
                - db
            networks:
                - my-network

networks: 
  my-network:
    driver: bridge

volumes:
    db-data:
    pgadmin-data: