
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/votacao}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration
    baseline-version: 1
    baseline-on-migrate: true
    user: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${PORT:8080}
  servlet:
    context-path: /votacao-api
