spring:
  application:
    name: vote-challenge
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydatabase}
    baseline-version: 1
    user: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}

  jackson:
    serialization:
      fail-on-empty-beans: false

flyway:
  baseline-on-migrate: true
  locations: classpath:/db/migration

server:
  port: 8081
  servlet:
    context-path: /api

