swagger: '2.0'

info:
  version: 1.0.0
  title: Votacao API
  description: No cooperativismo, cada associado possui um voto e as decisões são tomadas em assembleias, por votação. Imagine que você deve criar uma 
    solução para dispositivos móveis para gerenciar e participar dessas sessões de votação
paths:
  /pauta:
    post: 
      tags:
        - pauta
      summary: "Cadastra novas pautas"
      description: "Cadastra um nova pauta"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "postPauta"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/Pauta'      
      responses:
        201:
          description: Cadastro efetuado com sucesso
          schema:
            $ref: '#/definitions/PautaRetorno'
        400:
          description: Requisição inválida
  /pauta/contabilizacaoVotacao/{idPauta}:
    get: 
      tags:
        - pauta
      summary: "Consulta de pauta por id"
      description: "Retorna uma pauta com contabilizacao"
      operationId: getPautaById
      parameters:
        - name: idPauta
          in: path
          description: ID da pauta de retorno
          type: integer
          required: true
      consumes:
      - "application/json"
      responses:
        200:
          description: Consulta retornada com sucesso
          schema:
            $ref: '#/definitions/contabilizacaoVotacao'
        400:
          description: Requisição inválida
        404:
          description: Pauta não encontrada 
  /aberturaSessao:
    patch: 
      tags:
        - aberturaSessao
      summary: "Abre nova sessao"
      description: "Abre uma nova sessao de uma pauta"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "patchAberturaSessao"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/AberturaSessao'      
      responses:
        200:
          description: Sessao aberta com sucesso
        400:
          description: Requisição inválida
        404:
          description: Pauta não encontrada
  /voto:
    post: 
      tags:
        - voto
      summary: "gera um voto de um associado"
      description: "gera um voto de um associado de uma pauta"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: "postVoto"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/Voto'      
      responses:
        200:
          description: Voto gerado com sucesso
        400:
          description: Requisição inválida
        404:
          description: Pauta não encontrada                
      
definitions:

  Pauta:
    required:
      - nome
    type: object
    properties:
      nome:
        type: string
        example: pauta
        
  PautaRetorno:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 10
      nome:
        type: string
        example: pauta
      statusSessao:
        example: CRIADO
        enum:
          - CRIADO
          - ABERTO
          - FINALIZADO
          
  contabilizacaoVotacao:  
      type: object
      properties:  
        idPauta:
          type: integer
          format: int64
          example: 10 
        nomePauta:
          type: string
          example: pauta 
        tempoSessao:
          type: string
          format: date-time
          pattern: dd/MM/yyyy HH:mm:ss
          example: 01/01/2024 09:09:09
        statusSessao:
          example: CRIADO
          enum:
            - CRIADO
            - ABERTO
            - FINALIZADO  
        totalSim:
          type: integer
          format: int64
          example: 10
        totalNao:
          type: integer
          format: int64
          example: 10  
        total:
          type: integer
          format: int64
          example: 10  

  AberturaSessao:
    required:
      - idPauta
    type: object
    properties:
      idPauta:
        type: integer
        format: int64
        example: 10
      tempoSessao:
          type: string
          format: date-time
          pattern: dd/MM/yyyy HH:mm:ss
          example: 01/01/2024 09:09:09    
  Voto:
    required:
      - idPauta
      - idAssociado
      - voto
    type: object
    properties:
      idPauta:
        type: integer
        format: int64
        example: 10
      idAssociado:
        type: integer
        format: int64
        example: 10
      voto:
          type: string
          example: Sim
          enum:  
            - Sim
            - Não