create table if not exists associados
(
    id        bigint generated by default as identity primary key,
    cpf    varchar(11) not null unique,
    nome varchar(150) not null,
    status_cpf varchar(14) not null
);