create table if not exists sessoes
(
    id        bigint generated by default as identity primary key,
    pauta_id    bigint not null,
    data_abertura timestamp not null,
    data_encerramento timestamp not null,
    status_sessao varchar(8),
    resultado_sessao varchar(10)
);