CREATE TABLE PUBLIC.TAB_ASSOCIADO (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    CONSTRAINT TAB_ASSOCIADO_PK PRIMARY KEY (ID)
    );
