CREATE TABLE PUBLIC.TAB_PAUTA (
    ID SERIAL NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL,
    SESSAO_ID INTEGER,
    CONSTRAINT TAB_PAUTA_FK_SESSAO FOREIGN KEY (SESSAO_ID) REFERENCES PUBLIC.TAB_SESSAO(ID)
);
