CREATE TABLE PUBLIC.TAB_SESSAO (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DATA_INICIO TIMESTAMP,
    DATA_FIM TIMESTAMP,
    PAUTA_ID INTEGER NOT NULL,
    CONSTRAINT TAB_SESSAO_PK PRIMARY KEY (ID),
    CONSTRAINT SESSAO_FK FOREIGN KEY (PAUTA_ID) REFERENCES PUBLIC.TAB_PAUTA(ID)
);
