CREATE TABLE PUBLIC.TAB_VOTO (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PAUTA_ID INTEGER NOT NULL,
    ASSOCIADO_ID INTEGER NOT NULL,
    VOTO VARCHAR(4) NOT NULL,
    CONSTRAINT TAB_VOTO_PK PRIMARY KEY (ID),
    CONSTRAINT TAB_VOTO_FK_PAUTA FOREIGN KEY (PAUTA_ID) REFERENCES PUBLIC.TAB_PAUTA(ID),
    CONSTRAINT TAB_VOTO_FK_ASSOCIADO FOREIGN KEY (ASSOCIADO_ID) REFERENCES PUBLIC.TAB_ASSOCIADO(ID)
);
