# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - desafio-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://desafiodeploy.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_de7e2076b1ba421d8004385a909c83de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8ccdd492856d42898c423c70bd5bb448 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: desafiodeploy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de7e2076b1ba421d8004385a909c83de }}/votacao:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'desafio-deploy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ee31344f10cf44b8aa4f84db83c45194 }}
        images: 'desafiodeploy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_de7e2076b1ba421d8004385a909c83de }}/votacao:${{ github.sha }}'